### ISSUE TITLE
Stars Not showing 

### ISSUE THREAD

**Issue by sanribadu** [blackknight467/StarRatingBundle#10]
![screen shot 2016-12-04 at 00 25 29](https://cloud.githubusercontent.com/assets/24362219/20863101/4940297a-b9b8-11e6-9091-f8d379e20699.png)

Hello, 
 Thank you this bundle. its working in a form but the stars are not showing.

and please how can i show the rated stars from the form on html.twig. i mean how to display the already selected rated stars on html.twig.

**Comment by blackknight467** [comment]
hi @sanribadu, can you tell me how you're getting font awesome onto your webpage?

**Comment by sanribadu** [comment]
i am using bootstrap.

**Comment by blackknight467** [comment]
@sanribadu the bundle requires font awesome for it to work.

just put this into the head section of your page and it should work:

`<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

**Comment by sanribadu** [comment]
thank you. it works

**Comment by blackknight467** [comment]
glad to help.
