### ISSUE TITLE
it is possible to display stars on webpage

### ISSUE THREAD

**Issue by sanribadu** [blackknight467/StarRatingBundle#11]
please it is possible to display stars that have already been rated on webpage

**Comment by blackknight467** [comment]
you mean, not through a form.  Yes it is.  Just look at the [readme](https://github.com/blackknight467/StarRatingBundle#display-in-a-twig-template-using-the-rating-filter)

**Comment by sanribadu** [comment]
yes when i put the {{ someInteger|rating }}. i get error Variable "someInteger" does not exist

**Comment by blackknight467** [comment]
someInteger is an example.. you can put 4, you can put 3, you can a variable that exists on your page.  It's not literal, it's a place holder for your stuff.

**Comment by sanribadu** [comment]
ooh yeah got it. sorry for the silly new to php. thanks alot. it works
