### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by hamzarebaichkaw** [blackknight467/StarRatingBundle#17]
An exception has been thrown during the rendering of a template ("Notice: Object of class Symfony\Component\Form\FormView could not be converted to int")

**Comment by hamzarebaichkaw** [comment]
"exception" => Twig_Error_Runtime {#1601 ▼
    -lineno: 3
    -name: "StarRatingBundle:Display:ratingDisplay.html.twig"
    -rawMessage: "An exception has been thrown during the rendering of a template ("Notice: Object of class Symfony\Component\Form\FormView could not be converted to int")."
    -sourcePath: "/var/www/html/MMSS/vendor/blackknight467/star-rating-bundle/blackknight467/StarRatingBundle/Resources/views/Display/ratingDisplay.html.twig"
    -sourceCode: """
      <div class="rating">\n
        {% for i in 1..max %}\n
          <div class="{% if i <= stars %}star-full{% else %}star-empty{% endif %} {{ starSize }}"></div>\n
        {% endfor %}\n
      </div>
      """
    #message: "An exception has been thrown during the rendering of a template ("Notice: Object of class Symfony\Component\Form\FormView could not be converted to int")."
    #code: 0
    #file: "/var/www/html/MMSS/vendor/blackknight467/star-rating-bundle/blackknight467/StarRatingBundle/Resources/views/Display/ratingDisplay.html.twig"
    #line: 3

**Comment by blackknight467** [comment]
@hamzarebaichkaw 
can you post the twig you're using and the value of the variable you're passing to the rating filter?

**Comment by hamzarebaichkaw** [comment]
{{ form_start(commentaire, {'action': path('AjoutCommentaire') , 'method': 'POST','class':'comment-form'}) }}

<div class="form-group">

    {{ form_widget(commentaire.comment, { 'attr': {'class': 'form-control','cols':'45','rows':'8', 'placeholder': 'Write your comment here...'} }) }}
</div>

<div class="form-group">
    <p class="rating-stars">

    {{ form_widget(commentaire.rating|rating(5,"fa-3x") ) }}
    </p>
</div>


<button type="submit" class="eltd-btn eltd-btn-medium eltd-btn-solid eltd-btn-icon submit"><span class="eltd-btn-text">Publish</span>    <span aria-hidden="true" class="eltd-icon-font-elegant arrow_carrot-right "></span></button>

{{ form_end(commentaire) }}

**Comment by blackknight467** [comment]
@hamzarebaichkaw 
is "commentaire.rating" a string or an int?

**Comment by hamzarebaichkaw** [comment]
int

**Comment by blackknight467** [comment]
@hamzarebaichkaw 
oh, you're trying to use a filter in your form.  Just remove the rating filter and you should be fine.

```
{{ form_widget(commentaire.rating) }}
```

**Comment by hamzarebaichkaw** [comment]
@blackknight467 
thank you it worked
