### ISSUE TITLE
Usage in forms

### ISSUE THREAD

**Issue by Thonior** [blackknight467/StarRatingBundle#2]
Hi!

I am trying to use your bundle and I found that I cannot make it work in the form. 

I added in my form builder this line

->add('rating', 'rating', array('label' => 'Rating'));

and now I can see this field:

![image](https://cloud.githubusercontent.com/assets/2381263/7089989/2fe9035a-dfa0-11e4-8edb-eb0588a21892.png)

But it is not working as expected when clicking at some star. When I do mouseout the whole stars get deactivated again and the input field 

<input type="text" id="thonior_masterbundle_item_rating" name="thonior_masterbundle_item[rating]" required="required" class="rating" value="0.0">

still shows 0 as value.

May I be doing something wrong?

Another topic is if you made or thought on some way to make this work in ajax, anyway once I can make work the normal functionality I can implement on myself the ajax sendinf of the rating.

Thanks and best regars!

**Comment by blackknight467** [comment]
Sounds like you forgot to add the javascript.  please double check that you have it included it on your page.

**Comment by Thonior** [comment]
![image](https://cloud.githubusercontent.com/assets/2381263/7092741/80a979c8-dfb4-11e4-9fdd-695997a6fa95.png)
It's added

**Comment by blackknight467** [comment]
ok, can you look on the rendered webpage in your browser and see if there are any page assets that 404 or any javascript execution errors output to your browser's console.  

if everything has loaded correctly and you see no javascript errors after page load, then it's possible that there is a naming collision with something else on the page.

in your browser's developer tools, find the js block below:

    var labelWasClicked = function labelWasClicked(){
        var input = $(this).siblings().filter('input');
        input.val($(this).attr('data-value'));
    }

and put a breakpoint on the  var input = $(this).siblings().filter('input');

if the breakpoint isn't triggered then that means the listener isn't set up right.  I would need to see your html output in order to tell you what's wrong at that point.

if the breakpoint is triggered and it's still not working properly, my best guess it that you have some other js working on the same block

**Comment by Thonior** [comment]
I let you know on sunday, I am not in the computer anymore today and saturday. Thanks for your really fast response.

**Comment by Thonior** [comment]
I just put my hands on the project again today and it is working fine :s Probably was something cached. Sorry for the inconveniences

**Comment by sobha-radhakrishnan** [comment]
I am trying to use your bundle and I found that it is not displaying the star symbol.But instead some other symbols
Also i am not able to click on it to provide the rating.Am I doing something wrong?
Thyanks and Regards

**Comment by blackknight467** [comment]
@sobha-radhakrishnan what version of font awesome and symfony are you using?

**Comment by sobha-radhakrishnan** [comment]
I am using symfony2 and font awesome3.0.2
In composer.json i included 

{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "fontawesome/fontawesome",
        "version": "3.0.2",
        "dist": {
          "url": "https://github.com/FortAwesome/Font-Awesome/archive/v3.0.2.zip",
          "type": "zip"
        }
      }
    }
  ],
  "require": {
    "fontawesome/fontawesome": "3.0.2"
  }
}

Is there anything else to be done for fontawesome?Do i need to include anything in config.yml?

**Comment by blackknight467** [comment]
@sobha-radhakrishnan specific symfony 2 version please.

**Comment by sobha-radhakrishnan** [comment]
symfony 2.7 version

**Comment by sobha-radhakrishnan** [comment]
changing the version of font awesome as <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">resolved the issue with the star symbol..But I am not able to click on the stars.
Also  $builder->add('rating', 'rating', array('label' => 'Rating')); is just displaying a textbox with Rating label.
