### ISSUE TITLE
Read only field

### ISSUE THREAD

**Issue by Valousegawa** [blackknight467/StarRatingBundle#4]
Greetings,

I am actually using your bundle, and it is quite handy ! 
One problem thou : stars cannot be on readonly.

In fact, I have tried : 

```
$builder->add("rating", "rating", array(
                    "label" => 'Rating',
                    "read_only" => true
))
```

Field is on readonly attribute : 
```
readonly="readonly"
```
but I can still modify stars rating.

Is it a solution ?

Kind Regards,

**Comment by blackknight467** [comment]
@Valousegawa , thanks to @glynnforrest there is now a fix.  tag v1.0.3

**Comment by Valousegawa** [comment]
Ok I got it, I'll test that ASAP.
Thanks for reply.
