### ISSUE TITLE
This bundle will be updated to symfony 3?

### ISSUE THREAD

**Issue by n0ni0** [blackknight467/StarRatingBundle#6]
Hi, i'm trying to use the bundle with symfony 3  but forms have changed.

```php
<?php
    // ...
    $builder->add('rating', 'rating', array(
        'label' => 'Rating'
    ));
    // ...
````
Thanks.

**Comment by blackknight467** [comment]
@n0ni0 yes actually.  I was planning on working on that later today or tomorrow.

**Comment by blackknight467** [comment]
@n0ni0 i have pushed the update for symfony 3, enjoy.

https://github.com/blackknight467/StarRatingBundle/commit/b288302e2b97d3a8afc0c5d555ac0a9f879dbe5c
