### ISSUE TITLE
Could not load type "AppBundle\Form\RatingType"

### ISSUE THREAD

**Issue by nextsoftpl** [blackknight467/StarRatingBundle#8]
thank you for this bundle, however I have problem running it, what could have gone wrong?

**Comment by nextsoftpl** [comment]
Ok, I figured it out, had to import the class in form:
use blackknight467\StarRatingBundle\Form\RatingType as RatingType;

thank you :)

**Comment by blackknight467** [comment]
@nextsoftpl glad you figured it out.  If you have any further questions please let me know.  

Also now that you've been using it for a few days, do you have any thought or feedback about this?  Thanks!

**Comment by nextsoftpl** [comment]
working as expected, great work, thank you :) Maybe putting the 
`use blackknight467\StarRatingBundle\Form\RatingType as RatingType;`
in the README.md would be a good idea.
