### ISSUE TITLE
Is it possible to use it in a Handlebars file ?

### ISSUE THREAD

**Issue by odecharette** [blackknight467/StarRatingBundle#9]
Hi !

I'm using your bundle, and it is exactly what I need !
Working perfectly with Twig

My problem is that I now use handlebarsjs template file for a specific functionality in my symfony app.
Is there a equivalent of {{ someInteger|rating }} for handlebars ??

Thanks

**Comment by blackknight467** [comment]
@odecharette Currently StarRatingBundle only supports twig.  It shouldn't be too hard to add a handlebar helper though.  If you look in Extensions/StarRatingExtension.php you'll notice that the rating extension is basically just passing off the variables to a template to render.  If you decide to do this feel free to submit it as a pull request as i'd love to include handlebar support if possible.
